"use strict";

const ERROR_CATEGORY = Object.freeze({
  REQUEST_PROTOCOL: "request_protocol",
  QUERY_CONFLICT: "query_conflict",
  VALIDATION: "validation",
  CONCURRENCY: "concurrency",
  LIMIT_STRUCTURE_CAPABILITY: "limit_structure_capability",
  WRITE_PROOF_RECOVERY: "write_proof_recovery",
  INTERNAL: "internal",
});

const ERROR_CODE_CATEGORY = Object.freeze({
  INVALID_FRAGMENT: ERROR_CATEGORY.REQUEST_PROTOCOL,
  INVALID_REQUEST: ERROR_CATEGORY.REQUEST_PROTOCOL,
  OUTPUT_EXISTS: ERROR_CATEGORY.REQUEST_PROTOCOL,
  PROTOCOL_VERSION_UNSUPPORTED: ERROR_CATEGORY.REQUEST_PROTOCOL,
  REQUEST_ERROR: ERROR_CATEGORY.REQUEST_PROTOCOL,

  AMBIGUOUS_MATCH: ERROR_CATEGORY.QUERY_CONFLICT,
  EXPECTATION_FAILED: ERROR_CATEGORY.QUERY_CONFLICT,
  NO_MATCH: ERROR_CATEGORY.QUERY_CONFLICT,
  PRECONDITION_FAILED: ERROR_CATEGORY.QUERY_CONFLICT,
  SOURCE_CHANGED: ERROR_CATEGORY.QUERY_CONFLICT,
  TARGET_CHANGED: ERROR_CATEGORY.QUERY_CONFLICT,

  ANCHOR_CONFLICT: ERROR_CATEGORY.VALIDATION,
  CYCLE_DETECTED: ERROR_CATEGORY.VALIDATION,
  IDENTITY_VIOLATION: ERROR_CATEGORY.VALIDATION,
  INVALID_RESULT: ERROR_CATEGORY.VALIDATION,
  PROFILE_VIOLATION: ERROR_CATEGORY.VALIDATION,
  REFERENCE_VIOLATION: ERROR_CATEGORY.VALIDATION,
  VALIDATION_FAILED: ERROR_CATEGORY.VALIDATION,
  YAML_DIAGNOSTIC: ERROR_CATEGORY.VALIDATION,

  UNSAFE_CONCURRENCY: ERROR_CATEGORY.CONCURRENCY,

  CHANGE_LIMIT_EXCEEDED: ERROR_CATEGORY.LIMIT_STRUCTURE_CAPABILITY,
  CROSS_BOUNDARY_DEPENDENCY: ERROR_CATEGORY.LIMIT_STRUCTURE_CAPABILITY,
  UNSUPPORTED_EDIT_SHAPE: ERROR_CATEGORY.LIMIT_STRUCTURE_CAPABILITY,
  UNSUPPORTED_EDIT_UNIT: ERROR_CATEGORY.LIMIT_STRUCTURE_CAPABILITY,
  UNSUPPORTED_ENCODING: ERROR_CATEGORY.LIMIT_STRUCTURE_CAPABILITY,
  UNSUPPORTED_FILE_TYPE: ERROR_CATEGORY.LIMIT_STRUCTURE_CAPABILITY,

  ATOMIC_WRITE_UNAVAILABLE: ERROR_CATEGORY.WRITE_PROOF_RECOVERY,
  BYTE_GUARANTEE_FAILED: ERROR_CATEGORY.WRITE_PROOF_RECOVERY,
  RECOVERY_REQUIRED: ERROR_CATEGORY.WRITE_PROOF_RECOVERY,

  INTERNAL_ERROR: ERROR_CATEGORY.INTERNAL,
});

const ERROR_CATEGORY_EXIT_CODE = Object.freeze({
  [ERROR_CATEGORY.REQUEST_PROTOCOL]: 2,
  [ERROR_CATEGORY.QUERY_CONFLICT]: 3,
  [ERROR_CATEGORY.VALIDATION]: 4,
  [ERROR_CATEGORY.CONCURRENCY]: 5,
  [ERROR_CATEGORY.LIMIT_STRUCTURE_CAPABILITY]: 6,
  [ERROR_CATEGORY.WRITE_PROOF_RECOVERY]: 7,
  [ERROR_CATEGORY.INTERNAL]: 70,
});

function error_category_for_code(code) {
  return typeof code === "string" && Object.hasOwn(ERROR_CODE_CATEGORY, code)
    ? ERROR_CODE_CATEGORY[code]
    : ERROR_CATEGORY.INTERNAL;
}

class Yaml_patch_error extends Error {
  constructor(code, message, options = {}) {
    super(message, options.cause ? { cause: options.cause } : undefined);
    this.name = "Yaml_patch_error";
    this.code = code;
    this.category = error_category_for_code(code);
    this.recoverable = Boolean(options.recoverable);
    this.next_action = options.next_action || "review the error details";
    this.details = options.details || {};
  }
}

function is_yaml_patch_error(error) {
  return error instanceof Yaml_patch_error;
}

function request_error(message, options = {}) {
  throw new Yaml_patch_error("REQUEST_ERROR", message, options);
}

function exit_code_for_error(error) {
  if (!error || error.ok === true || (error.no_op === true && !error.code)) {
    return 0;
  }
  const category = error_category_for_code(error.code);
  return ERROR_CATEGORY_EXIT_CODE[category];
}

module.exports = {
  ERROR_CATEGORY,
  ERROR_CATEGORY_EXIT_CODE,
  ERROR_CODE_CATEGORY,
  Yaml_patch_error,
  error_category_for_code,
  exit_code_for_error,
  is_yaml_patch_error,
  request_error,
};
